config/routes.rb
Rails.application.routes.draw do
  resources :entries
  get 'home/index'

  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:foods, :activities, :feelings, :pains)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entries_helper.rb
module EntriesHelper

  def create_sorted_foods_tally
    food_tally = {}

    @entries.each do |entry|
      food_array = entry.foods.split(',')
      food_array.each do |food|
        if(food_tally.include?(food))
          food_tally[food] += 1
        else
          food_tally[food] = 1
        end
      end
    end
    food_tally = food_tally.sort_by{|k,v| -v}
    food_tally.to_h
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :foods %>
    <%= form.text_field :foods, class:"new-entry__field" %>
  </div>

  <div class="field">
    <%= form.label :activities %>
    <%= form.text_field :activities, class:"new-entry__field"  %>
  </div>

  <div class="field">
    <%= form.label :feelings %>
    <%= form.text_field :feelings, class:"new-entry__field"  %>
  </div>

  <div class="field">
    <%= form.label :pains %>
    <%= form.text_field :pains, class:"new-entry__field"  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Entries</h1>

<table class="entries__table">
  <thead>
    <tr>
      <th class="entries___time">Created</th>
      <th class="entries___foods">Foods</th>
      <th class="entries___activities">Activities</th>
      <th class="entries___feelings">Feelings</th>
      <th class="entries___pains">Pains</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= link_to time_ago_in_words(entry.created_at), entry %></td>
        <td><%= entry.foods %></td>
        <td><%= entry.activities %></td>
        <td><%= entry.feelings %></td>
        <td><%= entry.pains %></td>
        <td ><%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

<br><br>

<%# How can I access @entries in my home folder?  %>

<table>
  <% create_sorted_foods_tally.each_pair do |k,v| %>
    <tr>
      <td><%= v %></td>
      <td><%= k %></td>
    </tr>
  <% end %>
</table>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Foods:</strong>
  <%= @entry.foods %>
</p>

<p>
  <strong>Activities:</strong>
  <%= @entry.activities %>
</p>

<p>
  <strong>Feelings:</strong>
  <%= @entry.feelings %>
</p>

<p>
  <strong>Pains:</strong>
  <%= @entry.pains %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> 
<br> <br>
<%= link_to 'Back', entries_path %>
<br> <br>
<%= link_to 'Delete', @entry, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/home/_navbar_header.html.erb
<ul class="nav">

  <li>
    <%= link_to 'Data Doctor', root_path %>
  </li>

  <li>
    <%= link_to 'New Entry', new_entry_path %>
  </li>

  <li>
    <%= link_to 'View Entries', entries_path%>
  </li>

</ul>

app/views/home/index.html.erb
<h1>Data Doctor</h1>
<p>Take control of your health with the data doctor app.</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthAppV1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Kulim+Park&display=swap" rel="stylesheet">

  </head>

  <body>

    <%= render '/home/navbar_header' %>

    <%= yield %>
  </body>
</html>